### PR TITLE
Marketplace build

### PR DESCRIPTION
**Pull request by dnstommy**
@tmamedbekov I added a full visual studio solution for the audit code and an installation package that can be used on the Sitecore market place. I have tested this on a vanilla sim install with success.

### CODE REVIEW

**Comment by dnstommy** [comment]
Do you have a username on the sitecore marketplace?

**Comment by tmamedbekov** [comment]
Yes It is the same as my name Tony Mamedbekov

**Comment by dnstommy** [comment]
Do you want to try adding this to the market place or do you want me to?

**Comment by tmamedbekov** [comment]
I will go ahead and do it this week. Thank you for your help. I will add u as contributor.

**Pull request merged**
